global:
  scrape_interval: 15s
scrape_configs:
  - job_name: Prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: ’exoscale’
    file_sd_configs:
      - files:
          - /srv/service-discovery/config.json
        refresh_interval: 10s